version: '3.8'

services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - CI=true
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    network_mode: host